config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  
  resources :subjects do
	resources :ratings
  end
  
  get '/loggedIn', to: 'pages#loggedIn', as: :loggedIn
end

app/models/subject.rb
class Subject < ApplicationRecord
	 
	has_many :ratings, dependent: :destroy
	
	validates :subjectName, :site, :category, presence: true
	validates :subjectName, uniqueness: {scope: :site, 
	  message: "- this subject already exists for this site",
	  case_sensitive: false }
	  
	ratyrate_rateable 'rating'
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	
	def index
		@subjects = Subject.all
	end
	
	def show
		@subject = Subject.find(params[:id])
	end
	
	def new
		@subject = Subject.new
	end
	
	def edit
		@subject = Subject.find(params[:id])
	end
	
	def create
		@subject = Subject.new(subject_params)
		
		if @subject.save
		  redirect_to @subject
		else
		  render 'new'
		end
	end
	
	def update
		@subject = Subject.find(params[:id])
 
		if @subject.update(subject_params)
			redirect_to @subject
		else
			render 'edit'
		end
	end
	
	
	def destroy
	  @subject = Subject.find(params[:id])
	  @subject.destroy
	 
	  redirect_to subjects_path
	end
	

	
	private
		def subject_params
			params.require(:subject).permit(:subjectName, :site, :category)
		end
end

app/helpers/subjects_helper.rb
module SubjectsHelper

end

app/views/subjects/_form.html.erb
 <%= form_for @subject, url: subjects_path do |f| %>

  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subject.errors.count, "error") %> prohibited
        this subject from being saved:
      </h2>
      <ul>
        <% @subject.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :subjectName, "Subject" %>
    <%= f.text_field :subjectName, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :site %>
    <%= f.text_field :site, class: 'form-control' %>
  </div>
<%# would be cool to have this search as you type %>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
  </div>
  
  <%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/subjects/edit.html.erb

<h1>Edit subject</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<%= link_to 'New subject', new_subject_path %>

<table style="width:50%">
  <tr>
    <th>subjectName</th>
    <th>site</th>
	<th>category</th>
  </tr>


 
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.subjectName %></td>
      <td><%= subject.site %></td>
	  <td><%= subject.category %></td>
      <td><%= link_to 'Show', subject_path(subject) %></td>
	  <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
	  <td><%= link_to 'Destroy', subject_path(subject),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/subjects/new.html.erb

<h1>New subject</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb

<p>
  <strong>Subject:</strong>
  <%= @subject.subjectName %>
</p>
 
<p>
  <strong>Site:</strong>
  <%= @subject.site %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subject.category %>
</p>


   <%= rating_for @subject, "rating", {readonly: true} %>



<h2>Ratings</h2>
<%= render @subject.ratings %>

<h2>Add a rating:</h2>
<%= render 'ratings/form' %>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>